// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Webgame.Infrastructure.Persistence;

#nullable disable

namespace Webgame.Infrastructure.Migrations
{
    [DbContext(typeof(WebgameDbContext))]
    [Migration("20260324202129_MigrateCoinsToEnergy")]
    partial class MigrateCoinsToEnergy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Webgame.Domain.Players.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastActiveUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("Webgame.Domain.Players.Player", b =>
                {
                    b.OwnsOne("Webgame.Domain.Players.Stats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("PlayerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("AutoClickerLevel")
                                .HasColumnType("int")
                                .HasColumnName("AutoClickerLevel");

                            b1.Property<int>("ClickPower")
                                .HasColumnType("int")
                                .HasColumnName("ClickPower");

                            b1.Property<int>("ClickPowerLevel")
                                .HasColumnType("int")
                                .HasColumnName("ClickPowerLevel");

                            b1.Property<long>("Energy")
                                .HasColumnType("bigint")
                                .HasColumnName("Energy");

                            b1.Property<long>("Experience")
                                .HasColumnType("bigint")
                                .HasColumnName("Experience");

                            b1.Property<long>("ExperienceToNextLevel")
                                .HasColumnType("bigint")
                                .HasColumnName("ExperienceToNextLevel");

                            b1.Property<int>("Level")
                                .HasColumnType("int")
                                .HasColumnName("Level");

                            b1.Property<int>("OfflineCapLevel")
                                .HasColumnType("int")
                                .HasColumnName("OfflineCapLevel");

                            b1.Property<long>("StellarEnergy")
                                .HasColumnType("bigint")
                                .HasColumnName("StellarEnergy");

                            b1.Property<long>("StormEnergy")
                                .HasColumnType("bigint")
                                .HasColumnName("StormEnergy");

                            b1.Property<long>("TotalClicks")
                                .HasColumnType("bigint")
                                .HasColumnName("TotalClicks");

                            b1.Property<long>("TotalEnergyEarned")
                                .HasColumnType("bigint")
                                .HasColumnName("TotalEnergyEarned");

                            b1.Property<long>("TotalEnergySpent")
                                .HasColumnType("bigint")
                                .HasColumnName("TotalEnergySpent");

                            b1.Property<long>("TotalMerges")
                                .HasColumnType("bigint")
                                .HasColumnName("TotalMerges");

                            b1.HasKey("PlayerId");

                            b1.ToTable("Players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId");
                        });

                    b.Navigation("Stats")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
