// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Webgame.Infrastructure.Persistence;

#nullable disable

namespace Webgame.Infrastructure.Migrations
{
    [DbContext(typeof(WebgameDbContext))]
    [Migration("20260325185653_AddStellarEnergyUpgrades")]
    partial class AddStellarEnergyUpgrades
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Webgame.Domain.Players.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastActiveUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("Webgame.Domain.Players.Player", b =>
                {
                    b.OwnsOne("Webgame.Domain.Players.Board", "Board", b1 =>
                        {
                            b1.Property<Guid>("PlayerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("SlotCount")
                                .HasColumnType("int")
                                .HasColumnName("BoardSlotCount");

                            b1.HasKey("PlayerId");

                            b1.ToTable("Players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId");

                            b1.OwnsMany("Webgame.Domain.Players.CoreInstance", "Cores", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("PlayerId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("SlotIndex")
                                        .HasColumnType("int");

                                    b2.Property<int>("Tier")
                                        .HasColumnType("int");

                                    b2.HasKey("Id");

                                    b2.HasIndex("PlayerId");

                                    b2.ToTable("PlayerCores", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("PlayerId");
                                });

                            b1.Navigation("Cores");
                        });

                    b.OwnsOne("Webgame.Domain.Players.Stats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("PlayerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("BetterCores2Level")
                                .HasColumnType("int");

                            b1.Property<int>("BetterCoresLevel")
                                .HasColumnType("int");

                            b1.Property<long>("Energy")
                                .HasColumnType("bigint")
                                .HasColumnName("Energy");

                            b1.Property<long>("Experience")
                                .HasColumnType("bigint")
                                .HasColumnName("Experience");

                            b1.Property<long>("ExperienceToNextLevel")
                                .HasColumnType("bigint")
                                .HasColumnName("ExperienceToNextLevel");

                            b1.Property<int>("FasterCoresLevel")
                                .HasColumnType("int");

                            b1.Property<int>("FasterLevelUpLevel")
                                .HasColumnType("int");

                            b1.Property<int>("Level")
                                .HasColumnType("int")
                                .HasColumnName("Level");

                            b1.Property<int>("MoreStellarEnergyLevel")
                                .HasColumnType("int");

                            b1.Property<int>("OfflineCapLevel")
                                .HasColumnType("int")
                                .HasColumnName("OfflineCapLevel");

                            b1.Property<int>("OfflineProductionLevel")
                                .HasColumnType("int");

                            b1.Property<long>("StellarEnergy")
                                .HasColumnType("bigint")
                                .HasColumnName("StellarEnergy");

                            b1.Property<int>("StellarMoreStellarEnergyLevel")
                                .HasColumnType("int");

                            b1.Property<long>("StormEnergy")
                                .HasColumnType("bigint")
                                .HasColumnName("StormEnergy");

                            b1.Property<long>("TotalEnergyEarned")
                                .HasColumnType("bigint")
                                .HasColumnName("TotalEnergyEarned");

                            b1.Property<long>("TotalEnergySpent")
                                .HasColumnType("bigint")
                                .HasColumnName("TotalEnergySpent");

                            b1.Property<long>("TotalMerges")
                                .HasColumnType("bigint")
                                .HasColumnName("TotalMerges");

                            b1.HasKey("PlayerId");

                            b1.ToTable("Players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId");
                        });

                    b.Navigation("Board")
                        .IsRequired();

                    b.Navigation("Stats")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
